### ISSUE TITLE
Using dsaidemenu() in rocker docker containers

### ISSUE THREAD

**Issue by seabbs** [ahgroup/DSAIDE#51]
Everything is working well locally but when running the package in docker the links from the menu to the model apps don't seem to work.

This could well be a ports issue (this is often the case) for the rocker docker containers (https://github.com/rocker-org/rocker).

I'm not sure there is a fix so it might be worth just adding a note for those users running R in docker about alternative ways to access the content.

**Comment by andreashandel** [comment]
Thanks. Since shiny works through a local server, I can easily see how that can create problems. Since I don't use docker myself, I can't easily test and fix. If you find an easy fix, I'd be happy to include. But since most DSAIDE target users are likely not using a docker setup, I don't think this is too crucial. I will make a comment on the package website.
